"""
Setup script for building the frozen_memory C extension and sealing the
source integrity lockfile at build time.

Usage:
    python setup.py build_ext --inplace

The C extension is optional. If it cannot be compiled, the package
falls back to the ctypes-based implementation automatically.

Set SOVEREIGN_MCP_SKIP_EXT=1 to skip the C extension entirely and produce a
portable py3-none-any wheel. The .c source still ships in the wheel, so users
can compile it locally with `python setup.py build_ext --inplace`.
"""

import importlib.util
import os
import sys

from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext
from setuptools.command.build_py import build_py


def _seal_lockfile(package_dir):
    """
    Regenerate .integrity_lock.json for the package tree being built.

    integrity_lock is loaded directly from `package_dir` by file path rather
    than via `import sovereign_mcp.integrity_lock`. A normal import can
    resolve to an already-cached copy of the module from a different
    directory (this happens in the sdist -> wheel path, where the wheel is
    built from an extracted temp tree), which would seal the wrong tree and
    silently produce a broken distribution.
    """
    lock_py = os.path.join(package_dir, "integrity_lock.py")
    spec = importlib.util.spec_from_file_location("_sovereign_mcp_lockseal", lock_py)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    # The module derives its target directory from its own __file__, so
    # loading it from package_dir already points it at the right tree.
    assert os.path.dirname(os.path.abspath(module.__file__)) == os.path.abspath(package_dir)
    return module.generate_lockfile()


class RegenerateLockfileBuildPy(build_py):
    """
    Seal .integrity_lock.json immediately before the package is copied into
    the build tree.

    Without this the lockfile is whatever was last generated by hand. Any
    source edit made afterwards produces a distribution whose files do not
    match its own lockfile - and because __init__.py runs
    verify_integrity(strict=True) at import time, that distribution raises
    IntegrityViolation and refuses to load for every user. Both the 1.3.1 and
    1.3.2 wheels shipped in exactly that state.
    """

    def run(self):
        package_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "sovereign_mcp"
        )

        # The lockfile covers compiled artifacts (.pyd/.so) as a supply-chain
        # measure. In a portable build those artifacts are NOT packaged, so
        # sealing them would produce a lockfile referencing files the wheel
        # does not ship -- and verify_integrity() reports that as
        # "FILE DELETED" and refuses to load. Stale in-place build artifacts
        # are therefore removed before sealing a portable build.
        if os.environ.get("SOVEREIGN_MCP_SKIP_EXT") == "1":
            for entry in sorted(os.listdir(package_dir)):
                if entry.endswith((".pyd", ".so", ".dylib")):
                    stale = os.path.join(package_dir, entry)
                    os.remove(stale)
                    print(f"[build] Removed stale compiled artifact before sealing: {entry}")

        try:
            data = _seal_lockfile(package_dir)
            print(
                f"[build] Integrity lockfile sealed: {data['file_count']} files, "
                f"aggregate {data['aggregate_hash'][:16]}... "
                f"({package_dir})"
            )
        except Exception as e:
            # A distribution with a stale lockfile cannot be imported at all,
            # so fail the build rather than silently ship one.
            raise SystemExit(f"[build] FATAL: could not seal integrity lockfile: {e}")
        super().run()


class OptionalBuildExt(build_ext):
    """
    Build C extensions as optional.

    If compilation fails (e.g., no MSVC, no GCC), the build
    continues without the extension. The Python fallback
    (frozen_memory_fallback.py) handles this at runtime.
    """

    def build_extension(self, ext):
        try:
            super().build_extension(ext)
        except Exception as e:
            print(f"\n{'='*60}")
            print(f"WARNING: Could not compile C extension '{ext.name}'")
            print(f"Reason: {e}")
            print(f"The package will use the Python fallback instead.")
            print(f"{'='*60}\n")


frozen_memory_ext = Extension(
    "sovereign_mcp.frozen_memory",
    sources=["sovereign_mcp/frozen_memory.c"],
    language="c",
)

# Only add platform-specific libraries
if sys.platform == "win32":
    frozen_memory_ext.libraries = ["kernel32"]

# Building the extension makes the wheel platform-specific. The published
# wheel is portable (py3-none-any) and relies on the ctypes fallback, so the
# release build sets SOVEREIGN_MCP_SKIP_EXT=1.
_ext_modules = [] if os.environ.get("SOVEREIGN_MCP_SKIP_EXT") == "1" else [frozen_memory_ext]

setup(
    ext_modules=_ext_modules,
    cmdclass={
        "build_ext": OptionalBuildExt,
        "build_py": RegenerateLockfileBuildPy,
    },
)
